# permissions for end users to edit bucketstorages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bucketstorage-editor-role
rules:
- apiGroups:
  - cloudbucket.operators.rentit.com
  resources:
  - bucketstorages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudbucket.operators.rentit.com
  resources:
  - bucketstorages/status
  verbs:
  - get
