apiVersion: skaffold/v2beta28
kind: Config

# replace GCP_PROJECTID with your project id  


build:
  googleCloudBuild:
    projectId: GCP_PROJECTID
  artifacts:
  - image: us.gcr.io/GCP_PROJECTID/auth
    context: backend/auth-service
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: "src/**/*.ts"
          dest: .
  - image: us.gcr.io/GCP_PROJECTID/product
    context: backend/product-service
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
       - src: "src/**/*.ts"
         dest: .
  - image: us.gcr.io/GCP_PROJECTID/rentit
    context: backend/rentit-service
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
       - src: "src/**/*.ts"
         dest: .
  - image: us.gcr.io/GCP_PROJECTID/expiration
    context: backend/expiration-service
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
       - src: "src/**/*.ts"
         dest: .
  - image: us.gcr.io/GCP_PROJECTID/payment
    context: backend/payment-service
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
       - src: "src/**/*.ts"
         dest: .
  - image: us.gcr.io/GCP_PROJECTID/frontend
    context: frontend/rentit-client
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
       - src: "**/*.js"
         dest: .



deploy:
  kubectl:
    manifests:
    - ./operations/k8s/local/auth-deploy.yaml
    - ./operations/k8s/local/auth-mongodb-deploy.yaml
    - ./operations/k8s/local/product-deploy.yaml
    - ./operations/k8s/local/product-mongodb-deploy.yaml
    - ./operations/k8s/local/rentit-deploy.yaml
    - ./operations/k8s/local/rentit-mongodb-deploy.yaml
    - ./operations/k8s/local/expiration-deploy.yaml
    - ./operations/k8s/local/expiration-redis-deploy.yaml
    - ./operations/k8s/local/payment-deploy.yaml
    - ./operations/k8s/local/payment-mongodb-deploy.yaml
    - ./operations/k8s/local/frontend-deploy.yaml
    - ./operations/istio/dev/gw-vs.yaml
