apiVersion: skaffold/v2beta28
kind: Config


build:
  local:
    push: false
  artifacts:
  - image: rentit/auth
    custom:
      buildCommand: ./build.sh
      dependencies:
        paths:
        - ./backend/auth-service
    sync:
      manual:
        - src: "src/**/*.ts"
          dest: .

deploy:
  kubectl:
    manifests:
    - ./operations/k8sYamls/auth-deploy.yaml