apiVersion: skaffold/v2beta28
kind: Config


build:
  local:
    push: false
  artifacts:
  - image: rentit/auth
    context: backend/auth-service
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: "src/**/*.ts"
          dest: .
  - image: rentit/product
    context: backend/product-service
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
       - src: "src/**/*.ts"
         dest: .
  - image: rentit/rentit
    context: backend/rentit-service
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
       - src: "src/**/*.ts"
         dest: .


deploy:
  kubectl:
    manifests:
    - ./operations/k8s/local/auth-deploy.yaml
    - ./operations/k8s/local/auth-mongodb-deploy.yaml
    - ./operations/k8s/local/product-deploy.yaml
    - ./operations/k8s/local/product-mongodb-deploy.yaml
    - ./operations/k8s/local/rentit-deploy.yaml
    - ./operations/k8s/local/rentit-mongodb-deploy.yaml
