apiVersion: skaffold/v2beta28
kind: Config


build:
  local:
    push: false
  artifacts:
  - image: rentit/auth
    context: backend/auth-service
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: "src/**/*.ts"
          dest: .
  - image: rentit/product
    context: backend/product-service
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
       - src: "src/**/*.ts"
         dest: .
  - image: rentit/rentit
    context: backend/rentit-service
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
       - src: "src/**/*.ts"
         dest: .
  - image: rentit/expiration
    context: backend/expiration-service
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
       - src: "src/**/*.ts"
         dest: .
  - image: rentit/payment
    context: backend/payment-service
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
       - src: "src/**/*.ts"
         dest: .
  - image: rentit/frontend
    context: frontend/rentit-client-next
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
       - src: "**/*.js"
         dest: .
         #  - image: rentit/frontend
         #    context: frontend/rentit-client
         #    docker:
         #      dockerfile: Dockerfile
         #    sync:
         #      manual:
         #       - src: "**/*.js"
         #         dest: .


deploy:
  kubectl:
    manifests:
    - ./operations/k8s/local/auth-deploy.yaml
    - ./operations/k8s/local/auth-mongodb-deploy.yaml
    - ./operations/k8s/local/product-deploy.yaml
    - ./operations/k8s/local/product-mongodb-deploy.yaml
    - ./operations/k8s/local/rentit-deploy.yaml
    - ./operations/k8s/local/rentit-mongodb-deploy.yaml
    - ./operations/k8s/local/expiration-deploy.yaml
    - ./operations/k8s/local/expiration-redis-deploy.yaml
    - ./operations/k8s/local/payment-deploy.yaml
    - ./operations/k8s/local/payment-mongodb-deploy.yaml
    - ./operations/k8s/local/frontend-deploy.yaml
