apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ../../operations/k8sYamls/auth-deploy.yaml
build:
  local:
    push: false
  artifacts:
    - image: rentit/auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
