apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-postgresql-deploy
  namespace: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media-postgresql-app
  template:
    metadata:
      labels:
        app: media-postgresql-app
    spec:
      containers:
        - name: media-postgresql
          image: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: media-postgresql-service
  namespace: ingress-nginx
spec:
  selector:
    app: media-postgresql-app
  ports:
    - name: media-postgresql-port
      protocol: TCP
      port: 5432
      targetPort: 5432
