apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-deploy
  namespace: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media-app
  template:
    metadata:
      labels:
        app: media-app
    spec:
      containers:
        - name: media
          image: rentit/media
          imagePullPolicy: Never
          env:
            - name: POSTGRESQL_USER
              value: 'user'
            - name: POSTGRESQL_PASSWORD
              value: 'password'
            - name: POSTGRESQL_DB_NAME
              value: 'dbname'
            - name: POSTGRESQL_DB_URL
              value: 'mongodb://media-mongodb-service:27017/media'
---
apiVersion: v1
kind: Service
metadata:
  name: media-service
  namespace: ingress-nginx
spec:
  selector:
    app: media-app
  ports:
    - name: media-port
      protocol: TCP
      port: 8080
      targetPort: 8080
