apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-app
  template:
    metadata:
      labels:
        app: post-app
    spec:
      containers:
        - name: post
          image: rentit/post:1.0
