apiVersion: v1
kind: Service
metadata:
  name: post-service
spec:
  type: NodePort
  selector:
    app: post-app
  ports:
    - name: post-port
      protocol: TCP
      port: 4000
      targetPort: 4000
