apiVersion: skaffold/v2beta28
kind: Config

# replace GCP_PROJECTID with your project id  


build:
  googleCloudBuild:
    projectId: GCP_PROJECTID
    concurrency: 1
  artifacts:
  - image: us.gcr.io/GCP_PROJECTID/auth
    context: backend/auth-service
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: "src/**/*.ts"
          dest: .
  - image: us.gcr.io/GCP_PROJECTID/product
    context: backend/product-service
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
       - src: "src/**/*.ts"
         dest: .
  - image: us.gcr.io/GCP_PROJECTID/rentit
    context: backend/rentit-service
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
       - src: "src/**/*.ts"
         dest: .
  - image: us.gcr.io/GCP_PROJECTID/expiration
    context: backend/expiration-service
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
       - src: "src/**/*.ts"
         dest: .
  - image: us.gcr.io/GCP_PROJECTID/payment
    context: backend/payment-service
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
       - src: "src/**/*.ts"
         dest: .
  - image: us.gcr.io/GCP_PROJECTID/frontend
    context: frontend/rentit-client
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
       - src: "**/*.js"
         dest: .



deploy:
  kubectl:
    manifests:
    - ./devops/k8s/dev/auth-deploy.yaml
    - ./devops/k8s/dev/auth-mongodb-deploy.yaml
    - ./devops/k8s/dev/product-deploy.yaml
    - ./devops/k8s/dev/product-mongodb-deploy.yaml
    - ./devops/k8s/dev/rentit-deploy.yaml
    - ./devops/k8s/dev/rentit-mongodb-deploy.yaml
    - ./devops/k8s/dev/expiration-deploy.yaml
    - ./devops/k8s/dev/expiration-redis-deploy.yaml
    - ./devops/k8s/dev/payment-deploy.yaml
    - ./devops/k8s/dev/payment-mongodb-deploy.yaml
    - ./devops/k8s/dev/frontend-deploy.yaml
    - ./devops/k8s/dev/nats-deploy.yaml
