apiVersion: apps/v1
kind: Deployment
metadata:
  name: rentit-deploy
  namespace: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rentit-app
  template:
    metadata:
      labels:
        app: rentit-app
    spec:
      containers:
        - name: rentit
          image: rentit/rentit
          imagePullPolicy: Never
          env:
            - name: NATS_URL
              value: 'http://nats-service:4222'
            - name: NATS_CLUSTER_ID
              value: 'clusterIdRentit'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET_KEY
            - name: MONGO_DB_URL
              value: 'mongodb://rentit-mongodb-service:27017/rentit'
---
apiVersion: v1
kind: Service
metadata:
  name: rentit-service
spec:
  selector:
    app: rentit-app
  ports:
    - name: rentit-port
      protocol: TCP
      port: 3000
      targetPort: 3000
