apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration-app
  template:
    metadata:
      labels:
        app: expiration-app
    spec:
      containers:
        - name: expiration
          image: us.gcr.io/GCP_PROJECTID/expiration
          imagePullPolicy: Never
          env:
            - name: NATS_URL
              value: 'http://nats-service:4222'
            - name: NATS_CLUSTER_ID
              value: 'clusterIdRentit'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: REDIS_HOST
              value: expiration-redis-service
