apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-deploy
  namespace: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media-app
  template:
    metadata:
      labels:
        app: media-app
    spec:
      containers:
        - name: media
          image: us.gcr.io/GCP_PROJECTID/media
          imagePullPolicy: Never
          env:
            - name: NATS_URL
              value: 'http://nats-service:4222'
            - name: NATS_CLUSTER_ID
              value: 'clusterIdRentit'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET_KEY
            - name: MONGO_DB_URL
              value: 'mongodb://media-mongodb-service:27017/media'
---
apiVersion: v1
kind: Service
metadata:
  name: media-service
spec:
  selector:
    app: media-app
  ports:
    - name: media-port
      protocol: TCP
      port: 3000
      targetPort: 3000
