apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-app
  template:
    metadata:
      labels:
        app: product-app
    spec:
      containers:
        - name: product
          image: us.gcr.io/GCP_PROJECTID/product
          imagePullPolicy: IfNotPresent
          env:
            - name: NATS_URL
              value: 'http://nats-service:4222'
            - name: NATS_CLUSTER_ID
              value: 'clusterIdRentit'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET_KEY
            - name: MONGO_DB_URL
              value: 'mongodb://product-mongodb-service:27017/product'
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: default
spec:
  selector:
    app: product-app
  ports:
    - name: product-port
      protocol: TCP
      port: 3000
      targetPort: 3000
