apiVersion: apps/v1
kind: Deployment
metadata:
  name: rentit-mongodb-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rentit-mongodb-app
  template:
    metadata:
      labels:
        app: rentit-mongodb-app
    spec:
      containers:
        - name: rentit-mongodb
          image: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: rentit-mongodb-service
  namespace: default
spec:
  selector:
    app: rentit-mongodb-app
  ports:
    - name: rentit-mongodb-port
      protocol: TCP
      port: 27017
      targetPort: 27017
