name: auth-tests

on:
  pull_request:
    branches:
      - dev
    paths:
      - 'backend/auth-service/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd backend/auth-service && npm install && npm run test:ci
