name: product-tests

on:
  pull_request:
    branches:
      - dev
    paths:
      - 'backend/product-service/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd backend/product-service && npm install && npm run test:ci
